datasource:
  url: jdbc:sqlserver://localhost:1444;databaseName={db}
  username: sa
  password:
  driver-class-Name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  params:
    db: JZZF2013INFO
  hikari:
    minimum-idle: 3
    maximum-poolsize: 500
    auto-commit: true
    idle-timeout: 10000
    pool-name: DatebookHikariCP
    max-lifetime: 1800000
    connection-timeout: 30000